
package Pantallas;

import Controller.ControladorVistaCarteleraElectronica;
import Dominio.Parking;
import Dominio.Tarifario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class UICarteleraElectronica extends javax.swing.JFrame implements VistaCarteleraElectronica{

    /**
     * Creates new form UICarteleraElectronica
     */
    private final ControladorVistaCarteleraElectronica controlador;
    public UICarteleraElectronica(int fila) {
        initComponents();
        controlador = new ControladorVistaCarteleraElectronica(this, fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUno = new javax.swing.JTable();
        btnCerrarCartelera = new javax.swing.JButton();
        txtDisponibilidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Disponibilidad:");

        tblDos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo de vehiculo", "Precio/<UT>"
            }
        ));
        jScrollPane1.setViewportView(tblDos);

        tblUno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cochera", "Disponibilidad"
            }
        ));
        jScrollPane2.setViewportView(tblUno);

        btnCerrarCartelera.setText("Cerrar");
        btnCerrarCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCarteleraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarCartelera)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnCerrarCartelera)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCarteleraActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarCarteleraActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarCartelera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDos;
    private javax.swing.JTable tblUno;
    private javax.swing.JTextField txtDisponibilidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarDatosParking(Parking parking, ArrayList<Tarifario> tarifas) {
        txtDisponibilidad.setText(String.valueOf(parking.getLibres().size()));
        DefaultTableModel model = (DefaultTableModel) tblUno.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblDos.getModel();
        // Limpiar la tabla
        model.setRowCount(0);

        // Agregar fila para cochera de discapacitado
        model.addRow(new Object[]{"Discapacitado", parking.getDisponibilidadDiscapacitado()});

        // Agregar fila para cochera eléctrica
        model.addRow(new Object[]{"Eléctrico", parking.getDisponibilidadElectrico()});

        // Agregar fila para cochera de empleado
        model.addRow(new Object[]{"Empleado", parking.getDisponibilidadEmpleado()});
        
        model2.setRowCount(0);
        for (Tarifario t : tarifas) {
            Object[] fila = new Object[]{
                t.getTp().getDescripcion(), 
                t.getTarifa()
            };
            model2.addRow(fila);
        }
    }
}
