/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controller.ControladorVistaTableroDeControl;
import Dominio.Anomalia;
import Dominio.Estadia;
import Dominio.Parking;
import Servicios.Fachada;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class UITableroControl extends javax.swing.JFrame implements VistaTableroDeControl{

    private final ControladorVistaTableroDeControl controlador;
    /**
     * Creates new form TableroControl
     */
    public UITableroControl(ArrayList<Parking> parkings) {
        initComponents();
        controlador = new ControladorVistaTableroDeControl(this, parkings);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParkingsTablero = new javax.swing.JTable();
        btnPrecios = new javax.swing.JButton();
        btnCartelera = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtTotalEstadias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalParking = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnomaliasTablero = new javax.swing.JTable();
        chkMonitorearAnomalias = new javax.swing.JCheckBox();
        btnCerrarTablero = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estadias");

        tblParkingsTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parking", "#Ocupadas", "#Libres", "Estado", "Factor demanda", "#Estadias", "Multas", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblParkingsTablero);

        btnPrecios.setText("Precios");
        btnPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreciosActionPerformed(evt);
            }
        });

        btnCartelera.setText("Cartelera");
        btnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteleraActionPerformed(evt);
            }
        });

        txtTotalEstadias.setColumns(2);
        txtTotalEstadias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalEstadiasActionPerformed(evt);
            }
        });

        jLabel2.setText("Facturacion");

        txtTotalParking.setColumns(3);
        txtTotalParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalParkingActionPerformed(evt);
            }
        });

        tblAnomaliasTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha/Hora", "Propietario", "Codigo de anomalia", "Cochera"
            }
        ));
        jScrollPane2.setViewportView(tblAnomaliasTablero);

        chkMonitorearAnomalias.setText("Monitorear anomalias");
        chkMonitorearAnomalias.setToolTipText("");
        chkMonitorearAnomalias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMonitorearAnomaliasActionPerformed(evt);
            }
        });

        btnCerrarTablero.setText("Cerrar");
        btnCerrarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarTableroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalEstadias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkMonitorearAnomalias))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPrecios)
                                .addGap(18, 18, 18)
                                .addComponent(btnCartelera)))
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarTablero)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotalEstadias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCartelera)
                            .addComponent(btnPrecios))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkMonitorearAnomalias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnCerrarTablero)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btnPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreciosActionPerformed
    int filaSeleccionada = tblParkingsTablero.getSelectedRow();
    
    if (filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
        // Crear una instancia de UICarteleraElectronica y pasarle el objeto Parking como parámetro
            UIListaPrecios precios = new UIListaPrecios(filaSeleccionada);
            precios.setVisible(true);
    } else {
        // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila en la grilla.");
    }
    }//GEN-LAST:event_btnPreciosActionPerformed

    private void btnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraActionPerformed
     int filaSeleccionada = tblParkingsTablero.getSelectedRow();
    
    if (filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
        // Crear una instancia de UICarteleraElectronica y pasarle el objeto Parking como parámetro
            UICarteleraElectronica cartelera = new UICarteleraElectronica(filaSeleccionada);
            cartelera.setVisible(true);
    } else {
        // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila en la grilla.");
    }
    
    }//GEN-LAST:event_btnCarteleraActionPerformed

    private void txtTotalEstadiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEstadiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalEstadiasActionPerformed

    private void btnCerrarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTableroActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarTableroActionPerformed

    private void txtTotalParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalParkingActionPerformed

    private void chkMonitorearAnomaliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMonitorearAnomaliasActionPerformed
        LocalDateTime comienzoLista = LocalDateTime.now();
        if (chkMonitorearAnomalias.isSelected()) {
        controlador.setCheckboxSeleccionado(true, comienzoLista);
        }else{
        controlador.setCheckboxSeleccionado(false, comienzoLista);
        }
    }//GEN-LAST:event_chkMonitorearAnomaliasActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCartelera;
    private javax.swing.JButton btnCerrarTablero;
    private javax.swing.JButton btnPrecios;
    private javax.swing.JCheckBox chkMonitorearAnomalias;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblAnomaliasTablero;
    private javax.swing.JTable tblParkingsTablero;
    private javax.swing.JTextField txtTotalEstadias;
    private javax.swing.JTextField txtTotalParking;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTotalEstadiasParking(ArrayList<Estadia> estadias) {
       txtTotalEstadias.setText(String.valueOf(estadias.size()));
    }
     @Override
    public void mostrarMontoTotalParking(double montoTotal) {
       txtTotalParking.setText(String.valueOf(montoTotal));
       //TODO: MONTO TOTAL FACTURADO DE PARKINGS
    }
   @Override
    public void mostrarListaParking(ArrayList<Parking> parkings) {
        DefaultTableModel model = (DefaultTableModel) tblParkingsTablero.getModel();
        // Limpiar la tabla
        model.setRowCount(0);

        for (Parking pk : parkings) {
            Object[] fila = new Object[]{
                pk.getNombre(),
                pk.getOcupadas().size(), // TODO: Marcar ocupadas las cocheras
                pk.getLibres().size(),
                pk.getEstado(),
                pk.getFactorDemanda(),
                pk.getEstadias().size(), // Obtener estadias por parking
                pk.getSubtotalParkingMultas(), // Subtotal cobrado por multas ($)
                pk.getSubtotalParking() // Subtotal del parking ($)
            };
            model.addRow(fila);
        }
    }

    @Override
    public void mostrarListaAnomalias(ArrayList<Object[]> datos) {
         DefaultTableModel model = (DefaultTableModel) tblAnomaliasTablero.getModel();
        // Limpiar la tabla
        model.setRowCount(0);

        for (Object[] fila : datos) {
            model.addRow(fila);
        }
    }
    
}
